INSERT INTO USERS (ID ,BUDGET, NAME) VALUES (1, 11200.0, 'Peter');
INSERT INTO USERS (ID, BUDGET, NAME) VALUES (2, 20000.0, 'John');

INSERT INTO EXPENSE_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (1, 1, 650, 'Напої та снеки', 'Продукти', '2024-09-15');
INSERT INTO EXPENSE_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (2, 1, 1200, 'Похід в ресторан', 'Розваги', '2024-09-10');
INSERT INTO EXPENSE_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (3, 1, 300, 'Транспортні витрати', 'Транспорт', '2024-10-22');
INSERT INTO EXPENSE_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (4, 1, 800, 'Покупка одягу', 'Шопінг', '2024-10-05');

INSERT INTO INCOME_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (1, 1, 5000, 'Зарплата за червень', 'Зарплата', '2024-09-01');
INSERT INTO INCOME_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (2, 1, 200, 'Продаж старого телефону', 'Інше', '2024-09-10');
INSERT INTO INCOME_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (3, 1, 1500, 'Премія за продуктивність', 'Зарплата', '2024-10-15');
INSERT INTO INCOME_ENTITY (ID, USER_ID, AMOUNT, DESCRIPTION, CATEGORY, DATE) VALUES (4, 1, 800, 'Фріланс-проект', 'Фріланс', '2024-10-20');
